name: Executar Monitor de Preços

on:
  schedule:
    - cron: "*/30 * * * *" # Roda a cada 30 minutos
    # Para rodar a cada 1 hora, use:
    # - cron: "0 * * * *"

  workflow_dispatch:

jobs:
  run-monitor:
    runs-on: ubuntu-latest

    steps:
    - name: Baixar código do repositório
      uses: actions/checkout@v3

    - name: Configurar Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: 3.10

    - name: Instalar dependências
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Executar script monitor_precos.py
      run: python monitor_precos.py
