name: Executar Monitor de Preços

on:
  schedule:
    - cron: "*/30 * * * *"  # A cada 30 minutos
  workflow_dispatch:        # Permite rodar manualmente

jobs:
  run-monitor:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código do repositório
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"   # 🔹 Alterado para versão mais recente

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Rodar monitor de preços
        env:
          TOKEN: ${{ secrets.TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
          GSPREAD_CREDENTIALS: ${{ secrets.GSPREAD_CREDENTIALS }}
          
        run: |
          python -u monitor_ml.py
